version: '3'

networks:
    inventory-service:

services:
    nginx:
        image: nginx:stable
        container_name: ${APP_NAME}_nginx
        ports:
            - "8104:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - postgres
        networks:
            - inventory-service
    php:
        build: 
            context: .
            dockerfile: DockerFile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        networks:
            - inventory-service
    postgres:
        image: postgres:14.2-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5337:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - inventory-service