version: '3'

networks:
    inventory-service-dev:

services:
    nginx_inventory_dev:
        image: nginx:stable
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "8104:80"
        links:
            - php_inventory_dev
        volumes:
            - ~/Program/Dev/inventory-service/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ~/Program/Dev/inventory-service/docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php_inventory_dev
            - postgres_inventory_dev
        networks:
            - inventory-service-dev
    php_inventory_dev:
        image: ${APP_IMAGE_DEV}:${APP_IMAGE_DEV_TAG}
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ~/Program/Dev/inventory-service/storage:/var/www/html/storage:rw
            - ~/Program/Dev/inventory-service/.env:/var/www/html/.env:rw
        depends_on:
            - postgres_inventory_dev
        networks:
            - inventory-service-dev
    postgres_inventory_dev:
        image: postgres:14.2-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5337:5432"
        volumes:
            - ~/Program/Dev/inventory-service/docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - inventory-service-dev