version: '3'

networks:
    inventory-service-prod:

services:
    nginx_inventory_prod:
        image: nginx:stable
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "8004:80"
        links:
            - php_inventory_prod
        volumes:
            - ~/Program/inventory-service/docker/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf:rw
            - ~/Program/inventory-service/docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php_inventory_prod
            - postgres_inventory_prod
        networks:
            - inventory-service-prod
    php_inventory_prod:
        image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ~/Program/inventory-service/storage:/var/www/html/storage:rw
            - ~/Program/inventory-service/.env:/var/www/html/.env:rw
        depends_on:
            - postgres_inventory_prod
        networks:
            - inventory-service-prod
    postgres_inventory_prod:
        image: postgres:14.2-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5437:5432"
        volumes:
            - ~/Program/inventory-service/docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - inventory-service-prod